on:
  push:
    branches:
      - master
jobs:
  Install:
    name: install the packages
    runs-on: ubuntu-latest
  steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with: node-version: '16'
    name: Install
    run: npm install
    